[build]
  base = "/client"
  publish = "/client/build"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, GET, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
