[build]
  base = "client"
  publish = "client/build"
  command = "npm run build"

[build.environment]
  MONGODB_URI = "mongodb+srv://admin:UxhA7Z89iEgOZkMp@personalcluster.mhlbkqw.mongodb.net/?retryWrites=true&w=majority"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, GET, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
